services:

  site:
    build:
      context: services/site
      dockerfile: Dockerfile
    ports:
      - "12001:12001"
      - "12002:2345"
    volumes:
      - ../application:/app
      - ../.storage/go:/go
    environment:
      - TZ=Europe/Moscow

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=challengephp
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - ../.storage/postgres:/var/lib/postgresql/data
      - ./services/postgres/data:/var/backups/postgres
      - ./services/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "12003:5432"
